# Generated by Django 4.2 on 2023-04-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_surname2_alter_employee_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app.department', verbose_name='Отдел'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='mentor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app.mentor', verbose_name='Наставник'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.jobtitle', verbose_name='Должность'),
        ),
    ]
