# Generated by Django 4.2 on 2023-04-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_employee_date_time_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hash',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
