# Generated by Django 4.2 on 2023-04-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employee_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hash',
        ),
        migrations.AddField(
            model_name='employee',
            name='uuid',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
