# Generated by Django 4.2 on 2023-04-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_employee_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Должность'),
        ),
    ]
