# Generated by Django 4.2 on 2023-04-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_jobtitle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telegram_user_id',
            field=models.CharField(null=True),
        ),
    ]
